//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bhaptics.SDK2
{
    using System;
    using UnityEngine;
    
    
    public class BhapticsEvent
    {
        
        public const string RANDOMSTOMACH = "randomstomach";
        
        public const string HARD3 = "hard3";
        
        public const string CALM = "calm";
        
        public const string FULLSTOMACH = "fullstomach";
        
        public const string HARD4 = "hard4";
        
        public const string HARD2 = "hard2";
        
        public const string HARD1 = "hard1";
    }
}
